# This rule is not used by the project etherealpod itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the workload.sunday.io.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: etherealpod
    app.kubernetes.io/managed-by: kustomize
  name: etherealpod-editor-role
rules:
- apiGroups:
  - workload.sunday.io
  resources:
  - etherealpods
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - workload.sunday.io
  resources:
  - etherealpods/status
  verbs:
  - get
